msc/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'music/',include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from .import views
app_name = 'music'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(), name = 'index' ),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail' ),
    url(r'album/add/$',views.AlbumCreate.as_view(), name = 'album-add' ),
    url(r'album/logout$',views.Logout.as_view(), name = 'log' ),
    url(r'album/about$',views.AboutView.as_view(), name = 'aboutt' ),
   

]

music/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse

from django.db import models

# Create your models here.

class Album(models.Model):
	artist = models.CharField(max_length = 250)
	album_title = models.CharField(max_length = 500)
	genre = models.CharField(max_length = 100)
	album_logo = models.CharField(max_length = 1000)

	def get_absolute_url(self):
		return reverse('music:detail',kwargs={'pk':self.pk})

	def __str__(self):
		return self.album_title + '-' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE)
	file_type = models.CharField(max_length = 10)
	song_title = models.CharField(max_length = 250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

music/views.py
from django.views import generic

from django.views.generic.edit import CreateView
from .models import Album

class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields=['artist', 'album_title','genre', 'album_logo']

class Logout(generic.ListView):
	model=Album
	template_name = 'music/logout.html'

class AboutView(generic.ListView):
	model=Album
	template_name = 'music/about.html'

music/templates/music/Untitled Folder/about.html
<!DOCTYPE html>

<body>
DD
</body>

music/templates/music/Untitled Folder/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class = "container-fluid">

	<div class = "row">
		<div class = "col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class = "panel-body">
				<form class = "form-horizontal" action="" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{% include 'music/form-template.html' %}
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-success">Done</button>
					</div>			
				</div>
				</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

music/templates/music/Untitled Folder/base.html
<!DOCTYPE html>

<html lang = "en">

<head>
<meta charset="UTF-8">
<title>myuzikinator</title>
{% load staticfiles %}
<link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<link href = 'https://fonts.googleapis.com/css?family=Orbitron' rel ='stylesheet' type = 'text/css'>
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel = "stylesheet" type="text/css" href = "{% static 'music/style.css' %}" />




</head>

<body link = "f0e9fe" vlink="f0e9fe">

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class = "navbar-header">

			<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar" >
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>			
				<span class = "icon-bar"></span>						
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">Myuzikinator</a></div>
	
	<div class = "collapse navbar-collapse" id="topNavBar">
		<ul class = "nav navbar-nav">
			<li class = "active">
			<a href = "{% url 'music:index' %}">
				<span class="glyphicon glyphicon-record" aria-hidden = "true"></span>&nbsp; Playlists 
			
			</a></li>

							
			</ul>
			<form class = "navbar-form navbar-right" role = "search" method = "get" action = "#">
				<div class = "form-group">
				<input type = "text" class = "form-control" name = "q" value = "">	 </div>	
			<button type = "submit" class =" btn btn-info">Search</button>		

			</form>
		<ul class = "nav navbar-nav" navbar-"right">
			<li class = "">
			<a href = "{% url 'music:album-add' %}">
				<span class="glyphicon glyphicon-plus-sign" aria-hidden = "true"></span>&nbsp; New PlayList 
			
			</a></li>
			
			<li class = "">
			<a href = "{% url 'music:abo' %}">
				<span class="glyphicon glyphicon-question-sign" aria-hidden = "true"></span>&nbsp;About
			
			</a></li>
			<li class = "">
			<a href = "{% url 'music:log' %}">
				<span class="glyphicon glyphicon-king" aria-hidden = "true"></span>&nbsp; Logout 
			
			</a></li>

			
	</ul>	
	


		</div></div>
	
	

		



</nav>
{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/Untitled Folder/detail.html
{% extends 'music/base.html' %}


{% block body %}<center>
<img src="{{album.album_logo}}" style = "width : 325px;"></center>

<h1>
<font face="Showcard Gothic" color="94F114" size="7"><center>{{album.album_title}}</center></font></h1>

<h3><font face="Snap ITC" color="D803FE" size="6"><center>{{album.artist}}</center></font></h3>



	{% for song in album.song_set.all %}
		<center><font face="Comic Sans MS" color="F6FE03" size="5"><B>{{song.song_title}}<B></font></center>
		{% if song.is_favorite %}
			<img src="http://i.imgur.com/b9b13Rd.png"/>
		{% endif %}
	<br>
	{% endfor %}
	
{% endblock %}	

music/templates/music/Untitled Folder/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class = "control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

music/templates/music/Untitled Folder/index.html
<!DOCTYPE html>

<html>
<meta charset ="UTF-8">
{% extends 'music/base.html' %}

<body link = "f0e9fe" vlink="f0e9fe">

{% block body %}



{% if all_albums %}
	<strong style="color:#bed0fa;font-size:32px">PlayLists</strong><br><br>
	
		{% for album in all_albums %}
			

			<h3><a style = "color:#f9c3fc" href="{% url 'music:detail' album.id %}"><img src="{{album.album_logo}}" style = "width : 250px;">      {{ album.album_title}}-{{album.artist}}</a></h3>
		{% endfor %}
	
{% else %}
	<h3> You don't have any albums </h3>
{% endif %} 

{% endblock %}	

</body>
</html>

music/templates/music/Untitled Folder/logout.html
<body bgcolor = "white">
<br>

<h1 ><center><font face="comic sas ms">    THANKS FOR VISITING</font></center></h1>

<br>
<br>
<br>
<br>
<br>
<I>for any related queries</I> CONTACT
<br>Shirish Bajpai
<br>Shlok Srivastava</body>

music/templates/music/about.htm
<html>
<head>
<title>
about
</title>
<br><br><br>
<br>
<center>
<textarea rows="30" cols="100" align="center" style = "border:5px solid lightgreen; border-radius:15px; background-color:lightyellow" >
At w3schools.com you will learn how to make a website. We offer free tutorials in all web development technologies. 
</textarea>
</center>
</head>
<html>

music/templates/music/about.html
{% extends 'music/base.html' %}
<!DOCTYPE html>

<body>
<br><br><br>
<br>
<center>
<textarea rows="30" cols="100" align="center" style = "border:5px solid lightgreen; border-radius:15px; background-color:lightyellow" >

</textarea>
</body>

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class = "container-fluid">

	<div class = "row">
		<div class = "col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class = "panel-body">
				<form class = "form-horizontal" action="" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{% include 'music/form-template.html' %}
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="submit" class="btn btn-success">Done</button>
					</div>			
				</div>
				</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>

<html lang = "en">

<head>
<meta charset="UTF-8">
<title>myuzikinator</title>
{% load staticfiles %}
<link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<link href = 'https://fonts.googleapis.com/css?family=Orbitron' rel ='stylesheet' type = 'text/css'>
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel = "stylesheet" type="text/css" href = "{% static 'music/style.css' %}" />




</head>

<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class = "navbar-header">

			<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar" >
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>			
				<span class = "icon-bar"></span>						
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">Myuzikinator</a></div>
	
	<div class = "collapse navbar-collapse" id="topNavBar">
		<ul class = "nav navbar-nav">
			<li class = "active">
			<a href = "{% url 'music:index' %}">
				<span class="glyphicon glyphicon-record" aria-hidden = "true"></span>&nbsp; Playlists 
			
			</a></li>

					
			</ul>
			<form class = "navbar-form navbar-right" role = "search" method = "get" action = "#">
				<div class = "form-group">
				<input type = "text" class = "form-control" name = "q" value = "">	 </div>	
			<button type = "submit" class =" btn btn-info">Search</button>		

			</form>
		<ul class = "nav navbar-nav" navbar-"right">
			<li class = "">
			<a href = "{% url 'music:album-add' %}">
				<span class="glyphicon glyphicon-plus-sign" aria-hidden = "true"></span>&nbsp; New PlayList 
			
			</a></li>
<li class = "">
			<a href = "{% url 'music:aboutt' %}">
				<span class="glyphicon glyphicon-question-sign" aria-hidden = "true"></span>&nbsp;About
			
			</a></li>	
			<li class = "">
			<a href = "{% url 'music:log' %}">
				<span class="glyphicon glyphicon-king" aria-hidden = "true"></span>&nbsp; Logout 
			
			</a></li>

			
	</ul>	
	


		</div></div>
	
	

		



</nav>
{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}


{% block body %}<center>
<img src="{{album.album_logo}}" alt="Loading..." style = "width : 325px; border:5px solid lightblue; border-radius: 15px;"></center>

<h1>
<font face="Showcard Gothic" color="94F114" size="7"><center>{{album.album_title}}</center></font></h1>

<h3><font face="Snap ITC" color="f2d9ff" size="6"><center>{{album.artist}}</center></font></h3>



	{% for song in album.song_set.all %}
		<center><font face="Comic Sans MS" color="fbfab8" size="5"><B>{{song.song_title}}<B></font></center>
		{% if song.is_favorite %}
			<img src="http://i.imgur.com/b9b13Rd.png"/>
		{% endif %}
	<br>
	{% endfor %}
	
{% endblock %}	

music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class = "control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

music/templates/music/index.html
<!DOCTYPE html>

<html>
<meta charset ="UTF-8">
{% extends 'music/base.html' %}

<body link = "f0e9fe" vlink="f0e9fe">

{% block body %}



{% if all_albums %}
	<strong style="color:#bed0fa;font-size:32px">PlayLists</strong><br><br>
	
		{% for album in all_albums %}
			

			<h3><a style = "color:#f9c3fc" href="{% url 'music:detail' album.id %}"><img src="{{album.album_logo}}" alt="Loading..." style = "width : 250px; border:5px solid lightblue; border-radius: 15px;"">      {{ album.album_title}}-{{album.artist}}</a></h3>
		{% endfor %}
	
{% else %}
	<h3> You don't have any albums </h3>
{% endif %} 

{% endblock %}	

</body>
</html>

music/templates/music/logout.html
<body bgcolor = "white">
<br>

<h1 ><center><font face="comic sas ms">    THANKS FOR VISITING</font></center></h1>

<br>
<br>
<br>
<br>
<br>
<I>for any related queries</I> CONTACT
<br>Shirish Bajpai
<br>Shlok Srivastava
<br>Shashank Gupta</body>

music/templates/music/song.html
{% for album in all_album %}
	{% for so in album.song_set.all %}
		{{song.song_title}}
	{% endfor %}
{% endfor %}